#!/srv/epages/eproot/Perl/bin/perl


use strict;
use feature 'say';

use Getopt::Long;

use DE_EPAGES::Core::API::File qw( ExistsFile GetFileContent GetFileContentLines );
use DE_EPAGES::TLE::API::TLE qw ( TestSyntax );


my $Content = '';
my @Lines = ();

my $FileName;
GetOptions('file=s' => \$FileName);

if (defined $FileName) {
    die "File not found: $FileName" unless ExistsFile($FileName);
    $Content = ${GetFileContent($FileName)};
    @Lines = GetFileContentLines($FileName);
}
else {
    while (<>) {
        $Content .= $_;
        push @Lines, $_;
    }
}

my $Error = TestSyntax(\$Content);

if ($Error) {
    my $Message = $Error->vars->{'Message'};

    my @Yyparse = split(/\n/, $Error->vars->{'yyparse'});
    my $AfterNear = $Yyparse[0];
    my $QuotedAfterNear = quotemeta($AfterNear);

    my $LineNumber = $Error->vars->{'Line'};
    my $Line = $Lines[$LineNumber - 1];
    my @ParsedLine = split(/$QuotedAfterNear/, $Line);
    my $Near = $ParsedLine[0];
    $Near =~ s/^\s*//;

    print "$Message at line $LineNumber";
    print ", near $Near" if ($Near =~ m/\S/);
    print "\n";
}
else {
    say 'syntax ok';
}
